Repository Manzoomeh/BasisCore.Server.Edge, pull requests merged in 2024-08, with the labels that each got.

#87 Fix some issue in chunk encoding #86
  bclib/__init__.py
  bclib/context/client_source_context.py
  bclib/context/json_base_request_context.py
  bclib/context/restful_context.py
  bclib/context/web_context.py
  bclib/dispatcher/routing_dispatcher.py
  bclib/listener/web_message.py
  test/chunck_enconing/multi-server-fetch-source.py
Labels: bug

#90 Adding utility method for handel large data in chunk encoding #88
  bclib/__init__.py
  bclib/context/web_context.py
  test/chunck_enconing/multi-server-fetch-source.py
Labels: enhancement

#92 89 update logger section to manage multi part questions in schema log
  bclib/dispatcher/dispatcher.py
  bclib/logger/ilogger.py
  bclib/logger/log_object.py
  bclib/logger/schema_base_logger.py
Labels: enhancement

#96 Qamsari/95-edit-chunck-encoding-for-return-valid-json
  bclib/__init__.py
  test/chunck_enconing/multi-server-fetch-source.py
Labels: documentation
